spring:
  application:
    name: hotel
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/hotel_db
    driver-class-name: org.postgresql.Driver
  data:
    jdbc:
      dialect: postgresql
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /hotel